Repository rancher/kubewarden-ui, pull requests merged in 2023-07, with the labels that each got.

#408 Support airgap functionality within the UI
  .vscode/settings.json
  pkg/kubewarden/components/Dashboard/DashboardView.vue
  pkg/kubewarden/components/Dashboard/InstallView.vue
  pkg/kubewarden/components/DefaultsBanner.vue
  pkg/kubewarden/components/Policies/Create.vue
  pkg/kubewarden/components/Policies/PolicyDetail.vue
  pkg/kubewarden/components/TraceBanner.vue
  pkg/kubewarden/detail/policies.kubewarden.io.policyserver.vue
  pkg/kubewarden/l10n/en-us.yaml
  pkg/kubewarden/list/policies.kubewarden.io.policyserver.vue
  pkg/kubewarden/pages/c/_cluster/kubewarden/index.vue
  pkg/kubewarden/plugins/kubewarden-class.js
  pkg/kubewarden/store/kubewarden/actions.ts
  pkg/kubewarden/store/kubewarden/getters.ts
  pkg/kubewarden/store/kubewarden/index.ts
  pkg/kubewarden/store/kubewarden/mutations.ts
  pkg/kubewarden/utils/determine-airgap.ts
  tests/unit/components/Dashboard/DashboardView.spec.ts
Labels: area/air-gap

#409 Add policy server tests
  tests/e2e/components/table-row.ts
  tests/e2e/installation.spec.ts
  tests/e2e/overview.spec.ts
  tests/e2e/pages/admissionpolicies.page.ts
  tests/e2e/pages/basepage.ts
  tests/e2e/pages/basepolicypage.ts
  tests/e2e/pages/clusteradmissionpolicies.page.ts
  tests/e2e/pages/policyservers.page.ts
  tests/e2e/pages/rancher-ui.ts
  tests/e2e/policies.spec.ts
  tests/e2e/policyservers.spec.ts
Labels: area/qa

#418 Fix wait for rancher startup
  .github/workflows/playwright.yml
Labels: area/qa

#424 Bump 1.1.0
  package.json
  pkg/kubewarden/package.json
Labels: release/minor

#428 Reload page if extension installation gets stuck
  .github/workflows/playwright.yml
  tests/e2e/installation.spec.ts
  tests/e2e/pages/rancher-extensions.page.ts
Labels: area/qa

#429 Add Cluster Admission Policies test
  .github/workflows/playwright.yml
  tests/e2e/clusteradmissionpolicies.spec.ts
  tests/e2e/pages/basepolicypage.ts
  tests/e2e/pages/kubewarden.page.ts
  tests/e2e/pages/policyservers.page.ts
  tests/e2e/pages/rancher-common.page.ts
  tests/e2e/policyservers.spec.ts
Labels: area/qa

#433 Cluster name limit is 32 chars
  .github/workflows/playwright.yml
Labels: area/qa

#434 Schedule all tests in specific order
  .github/workflows/playwright.yml
  tests/e2e/00-installation.spec.ts
  tests/e2e/10-landing.spec.ts
  tests/e2e/30-policyservers.spec.ts
  tests/e2e/40-clusteradmissionpolicies.spec.ts
Labels: area/qa

#436 Add 2s timeout after waiting for policy to be active
  tests/e2e/40-clusteradmissionpolicies.spec.ts
  tests/e2e/pages/basepolicypage.ts
Labels: area/qa

#437 Code readability improvements
  tests/e2e/00-installation.spec.ts
  tests/e2e/10-landing.spec.ts
  tests/e2e/40-clusteradmissionpolicies.spec.ts
  tests/e2e/components/table-row.ts
  tests/e2e/pages/basepolicypage.ts
  tests/e2e/pages/overview.page.ts
  tests/e2e/pages/policyservers.page.ts
  tests/e2e/pages/rancher-common.page.ts
Labels: area/qa

#440 Add page reload wrapper for unstable rancher parts
  tests/e2e/00-installation.spec.ts
  tests/e2e/10-landing.spec.ts
  tests/e2e/components/table-row.ts
  tests/e2e/pages/basepolicypage.ts
  tests/e2e/pages/rancher-extensions.page.ts
  tests/e2e/pages/rancher-ui.ts
Labels: area/qa
