Repository rancher/kubewarden-ui, pull requests merged in 2023-03, with the labels that each got.

#284 Add dropdown for grafana
  pkg/kubewarden/assets/kubewarden-metrics-policy.json
  pkg/kubewarden/assets/kubewarden-metrics-policyserver.json
Labels: kind/enhancement

#283 Add e2e tests workflow
  .github/workflows/playwright.yml
  README.md
  tests/playwright.config.js
  tests/tests/policies.spec.js
Labels: area/qa

#285 Release 1.0.3
  package.json
  pkg/kubewarden/package.json
Labels: release/patch

#309 Release 1.0.4
  package.json
  pkg/kubewarden/package.json
Labels: release/patch
