Repository rancher/kubewarden-ui, pull requests merged in 2024-07, with the labels that each got.

#765 Respect show pre-release setting on initial installation
  jest.config.js
  pkg/kubewarden/chart/kubewarden/policy-server/General.vue
  pkg/kubewarden/components/Dashboard/InstallView.vue
  pkg/kubewarden/components/DefaultsBanner.vue
  pkg/kubewarden/components/SortableTableWrapper.vue
  pkg/kubewarden/plugins/kubewarden-class.js
  tests/unit/_templates_/controllerCharts.ts
  tests/unit/components/Dashboard/DashboardView.spec.ts
  tests/unit/components/Dashboard/InstallView.spec.ts
Labels: kind/bug

#777 Re-enable dependabot for tests
  .github/dependabot.yml
Labels: area/qa

#778 Fix dependabot time setting
  .github/dependabot.yml
Labels: area/qa

#786 Fix area/qa label
  .github/dependabot.yml
Labels: area/qa

#776 Remove readme step from policy creation - add slide-in for readme
  pkg/kubewarden/chart/kubewarden/admission/General.vue
  pkg/kubewarden/chart/kubewarden/admission/index.vue
  pkg/kubewarden/components/Policies/Config.vue
  pkg/kubewarden/components/Policies/Create.vue
  pkg/kubewarden/components/Policies/PolicyReadmePanel.vue
  pkg/kubewarden/l10n/en-us.yaml
  tests/unit/components/Policies/PolicyReadmePanel.spec.ts
Labels: kind/enhancement, area/policy

#788 Adapt tests for slide-in readme
  tests/e2e/00-installation.spec.ts
  tests/e2e/40-policies.spec.ts
  tests/e2e/components/rancher-ui.ts
  tests/e2e/pages/policies.page.ts
Labels: area/qa

#793 Pin playwright to 1.44 for node16 compatibility
  tests/package.json
  tests/yarn.lock
Labels: area/qa

#794 Fix resource fetching when user lacks permission
  pkg/kubewarden/chart/kubewarden/admission/ContextAware/index.vue
  pkg/kubewarden/chart/kubewarden/admission/General.vue
  pkg/kubewarden/chart/kubewarden/admission/NamespaceSelector/index.vue
  pkg/kubewarden/chart/kubewarden/admission/Rules/index.vue
  pkg/kubewarden/chart/kubewarden/policy-server/General.vue
  pkg/kubewarden/chart/kubewarden/policy-server/index.vue
  pkg/kubewarden/components/DefaultsBanner.vue
  pkg/kubewarden/components/Questions/SequenceTree.vue
  pkg/kubewarden/config/kubewarden.ts
  pkg/kubewarden/formatters/PolicyServerStatus.vue
  pkg/kubewarden/l10n/en-us.yaml
  pkg/kubewarden/list/policies.kubewarden.io.policyserver.vue
  pkg/kubewarden/pages/c/_cluster/kubewarden/index.vue
  pkg/kubewarden/plugins/policy-server-class.js
  pkg/kubewarden/types/rancher.ts
  pkg/kubewarden/utils/permissions.ts
Labels: kind/bug

#789 Set up tests for using ApplicationCollection
  tests/e2e/00-installation.spec.ts
  tests/e2e/60-telemetry.spec.ts
  tests/e2e/components/kubectl-shell.ts
  tests/e2e/components/rancher-ui.ts
  tests/e2e/rancher/rancher-apps.page.ts
  tests/e2e/rancher/rancher-extensions.page.ts
Labels: area/qa

#797 Release 1.6.2-rc.1
  package.json
  pkg/kubewarden/chart/kubewarden/policy-server/index.vue
  pkg/kubewarden/package.json
Labels: release/patch

#801 Bump 1.6.2
  package.json
  pkg/kubewarden/package.json
Labels: release/patch

#802 Fix fetching of policy server schema resourceFields
  package.json
  pkg/kubewarden/edit/policies.kubewarden.io.policyserver.vue
  pkg/kubewarden/package.json
  yarn.lock
Labels: kind/bug, area/policy-server, dependencies

#804 Run source tests on rancher 2.9 alpha
  .github/workflows/playwright.yml
Labels: area/qa

#817 Remove isValidAppVersion check for policy reports
  pkg/kubewarden/modules/policyReporter.ts
Labels: kind/bug, status/forwardport

#818 Bump 1.6.3
  package.json
  pkg/kubewarden/package.json
Labels: release/patch

#815 Add watch for active tab to refresh codemirror
  pkg/kubewarden/chart/kubewarden/admission/Settings.vue
  pkg/kubewarden/chart/kubewarden/admission/index.vue
Labels: kind/bug, area/policy

#805 Fix controller upgrade visibility
  pkg/kubewarden/components/Dashboard/DashboardView.vue
  pkg/kubewarden/utils/chart.ts
  tests/unit/utils/chart.spec.ts
Labels: kind/bug, status/backport-candidate

#821 Remove workaround for non-rc policy-server
  tests/e2e/30-policyservers.spec.ts
Labels: area/qa

#822 Install from rancher-latest repository
  .github/workflows/playwright.yml
Labels: area/qa

#827 Fix policyserver metrics datasource
  pkg/kubewarden/assets/kubewarden-dashboard-policyserver.json
  tests/e2e/60-telemetry.spec.ts
Labels: area/monitoring

#831 [Forwardport] Remove isValidAppVersion check for policy reports
  pkg/kubewarden/modules/policyReporter.ts
Labels: status/forwardport

#829 Fix metrics test for old rancher
  tests/e2e/00-installation.spec.ts
  tests/e2e/60-telemetry.spec.ts
Labels: area/qa
