Repository rancher/kubewarden-ui, pull requests merged in 2024-06, with the labels that each got.

#738 Fix version checks
  tests/e2e/50-policyreports.spec.ts
  tests/e2e/components/kubectl-shell.ts
  tests/e2e/components/rancher-ui.ts
Labels: area/qa

#751 Cancel previous job for the same PR
  .github/workflows/playwright.yml
Labels: area/qa

#752 Bump 1.6.1
  package.json
  pkg/kubewarden/package.json
Labels: release/patch

#758 Jaeger is no longer available from partners repo
  tests/e2e/40-policies.spec.ts
  tests/e2e/60-telemetry.spec.ts
  tests/e2e/rancher/rancher-apps.page.ts
Labels: area/qa

#759 Update policies in e2e tests
  tests/e2e/90-allpolicies.spec.ts
  tests/e2e/fleet/kubewarden/controller/fleet.yaml
  tests/e2e/pages/policies.page.ts
Labels: area/qa

#761 Extend upgrade timeout and add KW 1.13.0
  tests/e2e/00-installation.spec.ts
  tests/e2e/pages/kubewarden.page.ts
Labels: area/qa

#762 Use images from helm charts in fleet test
  tests/e2e/30-policyservers.spec.ts
  tests/e2e/fleet/cert-manager/fleet.yaml
  tests/e2e/fleet/kubewarden/controller/fleet.yaml
  tests/e2e/fleet/kubewarden/servers/default/fleet.yaml
Labels: area/qa

#734 Restructure policy creation layout
  pkg/kubewarden/components/Policies/Create.vue
  pkg/kubewarden/components/Policies/PolicyGrid.vue
  pkg/kubewarden/components/Policies/PolicyTable.vue
  pkg/kubewarden/components/SortableTableWrapper.vue
  pkg/kubewarden/components/TraceTable.vue
  pkg/kubewarden/config/table-headers.ts
  pkg/kubewarden/formatters/PolicyTableBadges.vue
  pkg/kubewarden/formatters/PolicyTableFeatures.vue
  pkg/kubewarden/formatters/PolicyTableResources.vue
  pkg/kubewarden/l10n/en-us.yaml
  tests/unit/components/Policies/PolicyGrid.spec.ts
  tests/unit/components/Policies/PolicyTable.spec.ts
Labels: kind/enhancement, area/ux

#763 Modify tests for table policy layout
  tests/e2e/00-installation.spec.ts
  tests/e2e/pages/policies.page.ts
Labels: area/qa

#768 Allow to select table columns/rows by index
  tests/e2e/components/rancher-ui.ts
  tests/e2e/components/table-row.ts
Labels: area/qa

#769 Add KW 1.14 to upgrade path
  tests/e2e/00-installation.spec.ts
  tests/e2e/rancher/rancher-apps.page.ts
Labels: area/qa
