Repository rancher/kubewarden-ui, pull requests merged in 2024-01, with the labels that each got.

#575 Add controller chart upgrade badge and tests
  .vscode/settings.json
  pkg/kubewarden/components/Dashboard/DashboardView.vue
  tests/unit/components/Dashboard/DashboardView.spec.ts
Labels: kind/enhancement

#576 Add readme tab to policy detail
  jest.config.js
  pkg/kubewarden/components/Dashboard/test.json
  pkg/kubewarden/components/Policies/PolicyDetail.vue
  tests/unit/components/Policies/PolicyDetail.spec.ts
  tests/unit/utils/wrapper.ts
Labels: area/policy

#582 Fix jaeger trace request operation to always search for validation
  pkg/kubewarden/modules/jaegerTracing.ts
Labels: area/tracing

#588 Restructure `refreshCharts` method
  pkg/kubewarden/components/Dashboard/InstallView.vue
  pkg/kubewarden/components/DefaultsBanner.vue
  pkg/kubewarden/components/MetricsTab.vue
  pkg/kubewarden/utils/chart.ts
  pkg/kubewarden/utils/handle-growl.ts
Labels: kind/bug

#593 Skip Container Resources policy test
  tests/e2e/90-allpolicies.spec.ts
  tests/e2e/pages/policies.page.ts
Labels: area/qa

#592 Fleet installation
  .github/workflows/playwright.yml
  tests/e2e/00-installation.spec.ts
  tests/e2e/10-landing.spec.ts
  tests/e2e/20-kubewarden.spec.ts
  tests/e2e/30-policyservers.spec.ts
  tests/e2e/40-policies.spec.ts
  tests/e2e/50-policyreports.spec.ts
  tests/e2e/60-telemetry.spec.ts
  tests/e2e/90-allpolicies.spec.ts
  tests/e2e/components/kubectl-shell.ts
  tests/e2e/components/navigation.ts
  tests/e2e/components/rancher-ui.ts
  tests/e2e/components/table-row.ts
  tests/e2e/fleet/cert-manager/fleet.yaml
  tests/e2e/fleet/kubewarden/controller/fleet.yaml
  tests/e2e/fleet/kubewarden/controller/values.yaml
  tests/e2e/fleet/kubewarden/crds/fleet.yaml
  tests/e2e/fleet/kubewarden/crds/values.yaml
  tests/e2e/fleet/kubewarden/servers/default/fleet.yaml
  tests/e2e/fleet/kubewarden/servers/default/values.yaml
  tests/e2e/fleet/kubewarden/servers/ps-fleet/fleet.yaml
  tests/e2e/fleet/kubewarden/servers/ps-fleet/pod-privileged.yaml
  tests/e2e/fleet/kubewarden/servers/ps-fleet/server.yaml
  tests/e2e/pages/kubewarden.page.ts
  tests/e2e/pages/policies.page.ts
  tests/e2e/pages/policyreporter.page.ts
  tests/e2e/pages/policyservers.page.ts
  tests/e2e/pages/telemetry.page.ts
  tests/e2e/rancher/basepage.ts
  tests/e2e/rancher/rancher-apps.page.ts
  tests/e2e/rancher/rancher-common.page.ts
  tests/e2e/rancher/rancher-extensions.page.ts
  tests/e2e/rancher/rancher-fleet.page.ts
  tests/e2e/rancher/rancher-test.ts
  tests/package.json
  tests/yarn.lock
Labels: area/qa

#596 Add Share PID namespace policy
  tests/e2e/pages/policies.page.ts
Labels: area/qa
