Repository rancher/kubewarden-ui, pull requests merged in 2024-03, with the labels that each got.

#631 Add check for context-aware & mutation labels
  tests/e2e/00-installation.spec.ts
  tests/e2e/pages/policies.page.ts
Labels: area/qa

#635 Bump 1.3.5
  package.json
  pkg/kubewarden/package.json
Labels: release/patch

#640 add banner to dashboard to inform user of about policy reporter compatibility
  package.json
  pkg/kubewarden/components/Dashboard/DashboardView.vue
  pkg/kubewarden/l10n/en-us.yaml
  pkg/kubewarden/modules/policyReporter.ts
  tests/unit/components/Dashboard/DashboardView.spec.ts
  yarn.lock
Labels: kind/enhancement

#644 Check policy server image with semver
  tests/e2e/00-installation.spec.ts
  tests/e2e/30-policyservers.spec.ts
Labels: area/qa

#647 Fix missing semver package
  tests/package.json
  tests/yarn.lock
Labels: area/qa

#648 fix issue with semver assertion for banners
  pkg/kubewarden/components/Dashboard/DashboardView.vue
  pkg/kubewarden/modules/policyReporter.ts
Labels: kind/bug

#651 Install 1.11.0-rc for PR tests
  tests/e2e/00-installation.spec.ts
  tests/e2e/pages/kubewarden.page.ts
Labels: area/qa

#652 Fixup: Install 1.11.0-rc for PR tests
  tests/e2e/00-installation.spec.ts
  tests/e2e/30-policyservers.spec.ts
Labels: area/qa

#636 recreate PR 616 - refactor policy server based on new data structure
  pkg/kubewarden/components/PolicyReporter/ResourceTab.vue
  pkg/kubewarden/components/PolicyReporter/index.vue
  pkg/kubewarden/config/kubewarden.ts
  pkg/kubewarden/config/table-headers.ts
  pkg/kubewarden/formatters/PolicyReportSummary.vue
  pkg/kubewarden/l10n/en-us.yaml
  pkg/kubewarden/modules/policyReporter.ts
  pkg/kubewarden/types.ts
  pkg/kubewarden/types/kubewarden.ts
  pkg/kubewarden/types/policy-reporter.ts
  pkg/kubewarden/types/wgpolicyk8s.io.ts
  tests/unit/_templates_/policyReports.ts
  tests/unit/components/PolicyReporter/ResourceTab.spec.ts
  tests/unit/modules/policyReporter.spec.ts
Labels: kind/bug, area/policy-reporter

#650 Recreate PR 621 - Limit policy reports to kubewarden controller version
  pkg/kubewarden/modules/kubewardenController.ts
  pkg/kubewarden/modules/policyReporter.ts
  tests/unit/_templates_/controllerApp.ts
  tests/unit/modules/kubewardenController.spec.ts
  tests/unit/modules/policyReporter.spec.ts
Labels: kind/bug, area/policy-reporter

#654 Fixup: Install 1.11.0-rc for PR tests
  tests/e2e/00-installation.spec.ts
Labels: area/qa

#657 Fix bug Projects/Namespaces show only last policyreport
  pkg/kubewarden/formatters/PolicyReportSummary.vue
  pkg/kubewarden/modules/policyReporter.ts
Labels: kind/bug

#661 Official extensions are available on prime only
  tests/e2e/00-installation.spec.ts
  tests/e2e/rancher/rancher-extensions.page.ts
  tests/e2e/rancher/rancher-fleet.page.ts
Labels: area/qa

#662 fix grafana url
  pkg/kubewarden/components/MetricsTab.vue
Labels: kind/bug

#663 UI test fixes
  tests/e2e/00-installation.spec.ts
  tests/e2e/60-telemetry.spec.ts
  tests/e2e/rancher/rancher-extensions.page.ts
Labels: area/qa

#666 Add PVC StorageClass Validator policy
  tests/e2e/90-allpolicies.spec.ts
  tests/e2e/pages/policies.page.ts
  tests/e2e/rancher/rancher-common.page.ts
Labels: area/qa

#668 Install tags and releases on rancher prime
  .github/workflows/playwright.yml
  tests/e2e/fleet/kubewarden/controller/fleet.yaml
  tests/e2e/fleet/kubewarden/crds/fleet.yaml
  tests/e2e/fleet/kubewarden/servers/default/fleet.yaml
  tests/e2e/fleet/kubewarden/servers/ps-fleet/fleet.yaml
  tests/e2e/rancher/rancher-apps.page.ts
Labels: area/qa

#671 Fix latest versions check in fleet test
  tests/e2e/30-policyservers.spec.ts
Labels: area/qa

#674 Check kubewarden logs for errors
  tests/e2e/00-installation.spec.ts
  tests/e2e/components/kubectl-base.ts
Labels: area/qa
