Repository rancher/kubewarden-ui, pull requests merged in 2024-11, with the labels that each got.

#941 Fix tests for Vue3 compliance
  .github/workflows/playwright.yml
  tests/e2e/00-installation.spec.ts
  tests/e2e/10-landing.spec.ts
  tests/e2e/60-telemetry.spec.ts
  tests/e2e/components/navigation.ts
  tests/e2e/components/rancher-ui.ts
  tests/e2e/pages/policyservers.page.ts
Labels: area/qa, area/vue3

#949 Remove cert-manager step from main installation
  pkg/kubewarden/components/Dashboard/InstallView.vue
  pkg/kubewarden/components/MetricsChecklist.vue
  pkg/kubewarden/components/TraceChecklist.vue
  pkg/kubewarden/components/TraceTable.vue
  pkg/kubewarden/l10n/en-us.yaml
  tests/unit/components/Dashboard/InstallView.spec.ts
Labels: kind/enhancement, status/backport-candidate

#956 Install cert-manager on imported clusters
  tests/e2e/60-telemetry.spec.ts
Labels: area/qa

#819 Add policy report results to dashboard view
  pkg/kubewarden/components/Dashboard/Card.vue
  pkg/kubewarden/components/Dashboard/DashboardView.vue
  pkg/kubewarden/components/Dashboard/Masthead.vue
  pkg/kubewarden/components/Dashboard/Modes.vue
  pkg/kubewarden/components/Dashboard/Reports.vue
  pkg/kubewarden/components/Dashboard/ReportsGauge.vue
  pkg/kubewarden/components/Graph/Bar.vue
  pkg/kubewarden/config/table-headers.ts
  pkg/kubewarden/l10n/en-us.yaml
  tests/unit/components/Dashboard/DashboardView.spec.ts
  tests/unit/components/Dashboard/Masthead.spec.ts
Labels: kind/enhancement, area/policy-reporter

#862 Update tests for new dashboard view
  tests/e2e/10-landing.spec.ts
  tests/e2e/20-kubewarden.spec.ts
  tests/e2e/pages/kubewarden.page.ts
Labels: area/qa

#955 Check for objectset.rio.cattle.io/applied annotation for policy source
  pkg/kubewarden/plugins/policy-class.js
Labels: kind/bug, area/policy, status/backport-candidate

#957 Add second maintanence branch for rancher 2.9
  .github/workflows/playwright.yml
  tests/e2e/pages/kubewarden.page.ts
  tests/e2e/rancher/rancher-extensions.page.ts
Labels: area/qa

#960 Bump 3.0.0-rc.2
  package.json
  pkg/kubewarden/package.json
Labels: release/rc

#961 [Backport] Check for objectset.rio.cattle.io/applied annotation for policy source
  pkg/kubewarden/plugins/policy-class.js
Labels: status/backport

#965 Add rancher 2.10 to test matrix
  .github/workflows/playwright.yml
  tests/e2e/00-installation.spec.ts
Labels: area/qa

#966 Bump 3.0.0
  package.json
  pkg/kubewarden/package.json
Labels: release/major

#963 [Backport] fix tracing and metrics controller app check
  package.json
  pkg/kubewarden/components/MetricsTab.vue
  pkg/kubewarden/components/TraceTable.vue
  yarn.lock
Labels: dependencies, status/backport

#971 Trigger PR tests also on maintenance branches
  .github/workflows/playwright.yml
Labels: area/qa

#972 Bump 2.1.0-rc.1
  package.json
  pkg/kubewarden/package.json
Labels: release/minor, release/rc

#970 [2.9] Backport e2e test fixes to rancher 2.9
  tests/e2e/00-installation.spec.ts
  tests/e2e/40-policies.spec.ts
  tests/e2e/components/rancher-ui.ts
  tests/e2e/pages/kubewarden.page.ts
  tests/e2e/pages/policyservers.page.ts
  tests/e2e/rancher/rancher-apps.page.ts
Labels: area/qa

#964 [Backport] fix tracing and metrics controller app check
  package.json
  pkg/kubewarden/components/MetricsChecklist.vue
  pkg/kubewarden/components/MetricsTab.vue
  pkg/kubewarden/components/TraceTable.vue
  yarn.lock
Labels: dependencies, status/backport

#973 Bump 1.6.5-rc.1
  package.json
  pkg/kubewarden/package.json
Labels: release/patch, release/rc

#976 [2.8] Update e2e workflow for maintenance PRs
  .github/workflows/playwright.yml
Labels: area/qa

#977 Fix typo in e2e workflow
  .github/workflows/playwright.yml
Labels: area/qa

#978 Fix typo in e2e workflow
  .github/workflows/playwright.yml
Labels: area/qa

#975 Bump 1.6.5
  package.json
  pkg/kubewarden/package.json
Labels: release/patch

#981 Fix for issue#898 is available only in UI > v3.0
  tests/e2e/40-policies.spec.ts
Labels: area/qa

#982 Fix beta installation in upgrade tests
  tests/e2e/00-installation.spec.ts
  tests/e2e/rancher/rancher-apps.page.ts
Labels: area/qa

#983 [2.9] Fix beta installation in upgrade tests
  tests/e2e/00-installation.spec.ts
  tests/e2e/rancher/rancher-apps.page.ts
Labels: area/qa

#985 Fix version check for defaults chart settings route
  pkg/kubewarden/models/policies.kubewarden.io.clusteradmissionpolicy.js
  pkg/kubewarden/plugins/policy-class.js
Labels: status/backport

#988 1.6.6-rc.1 bump
  package.json
  pkg/kubewarden/package.json
Labels: release/rc

#989 Remove growl message when whitelist-domain fetch unsuccessful
  pkg/kubewarden/utils/determine-airgap.ts
Labels: area/ux, area/air-gap, status/backport-candidate

#994 [2.8] Bump playwright to v1.49.0
  tests/package.json
  tests/yarn.lock
Labels: area/qa, status/backport

#995 [2.9] Bump playwright to v1.49.0
  tests/package.json
  tests/yarn.lock
Labels: area/qa, status/backport

#996 Bump 1.6.6
  package.json
  pkg/kubewarden/package.json
Labels: release/patch
