Repository rancher/kubewarden-ui, pull requests merged in 2024-02, with the labels that each got.

#597 Run tests on imported cluster
  tests/e2e/00-installation.spec.ts
  tests/e2e/10-landing.spec.ts
  tests/e2e/60-telemetry.spec.ts
  tests/e2e/90-allpolicies.spec.ts
  tests/e2e/components/kubectl-shell.ts
  tests/e2e/components/navigation.ts
  tests/e2e/pages/kubewarden.page.ts
  tests/e2e/pages/policies.page.ts
  tests/e2e/pages/policyreporter.page.ts
  tests/e2e/pages/policyservers.page.ts
  tests/e2e/rancher/rancher-apps.page.ts
  tests/e2e/rancher/rancher-common.page.ts
  tests/e2e/rancher/rancher-extensions.page.ts
  tests/e2e/rancher/rancher-fleet.page.ts
  tests/global-setup.ts
Labels: area/qa

#598 Add Unique service selector policy test
  tests/e2e/pages/policies.page.ts
Labels: area/qa

#601 Add warning banner to Metrics checklist for conflicting configmaps
  pkg/kubewarden/components/MetricsChecklist.vue
  pkg/kubewarden/components/MetricsTab.vue
  pkg/kubewarden/l10n/en-us.yaml
  tests/unit/components/MetricsChecklist.spec.ts
Labels: kind/bug, area/monitoring

#604 Bump 1.3.4
  package.json
  pkg/kubewarden/package.json
Labels: release/patch

#608 Kubectl shell in canvas
  tests/e2e/components/kubectl-base.ts
  tests/e2e/components/kubectl-canvas.ts
  tests/e2e/components/kubectl-xterm.ts
  tests/e2e/pages/kubewarden.page.ts
  tests/e2e/rancher/rancher-apps.page.ts
  tests/e2e/rancher/rancher-test.ts
  tests/e2e/screenshots/chromium/shell-EXITSTATUS-0.png
  tests/e2e/screenshots/chromium/shell-EXITSTATUS-1.png
  tests/e2e/screenshots/chromium/shell-EXITSTATUS-NaN.png
  tests/e2e/screenshots/firefox/shell-EXITSTATUS-0.png
  tests/e2e/screenshots/firefox/shell-EXITSTATUS-1.png
  tests/e2e/screenshots/firefox/shell-EXITSTATUS-NaN.png
  tests/playwright.config.ts
Labels: area/qa

#610 Allow availability of pre-release policies in PolicyGrid
  pkg/kubewarden/components/Policies/PolicyGrid.vue
  pkg/kubewarden/modules/artifacthub.ts
  tests/unit/components/Policies/PolicyGrid.spec.ts
  tests/unit/templates/policyPackages.js
  tests/unit/templates/schemas.js
Labels: kind/bug

#612 Fix artifacthub package parsing by repository url
  jest.config.js
  package.json
  pkg/kubewarden/components/Policies/Create.vue
  pkg/kubewarden/package.json
  tests/unit/FixJSDOMEnvironment.ts
  tests/unit/components/MetricsChecklist.spec.ts
  tests/unit/components/Policies/Create.spec.ts
  tests/unit/components/Policies/PolicyGrid.spec.ts
  tests/unit/templates/policyPackages.js
  tests/unit/utils/wrapper.ts
Labels: kind/bug, area/policy

#615 Add upgrade test
  .github/workflows/playwright.yml
  tests/README.md
  tests/e2e/00-installation.spec.ts
  tests/e2e/60-telemetry.spec.ts
  tests/e2e/components/kubectl-base.ts
  tests/e2e/components/navigation.ts
  tests/e2e/components/rancher-ui.ts
  tests/e2e/pages/kubewarden.page.ts
  tests/e2e/pages/policyservers.page.ts
  tests/e2e/rancher/rancher-apps.page.ts
  tests/e2e/rancher/rancher-fleet.page.ts
Labels: area/qa

#616 Refactor policy report filtering to match new resource based schema
  package.json
  pkg/kubewarden/components/PolicyReporter/ResourceTab.vue
  pkg/kubewarden/components/PolicyReporter/index.vue
  pkg/kubewarden/config/kubewarden.ts
  pkg/kubewarden/config/table-headers.ts
  pkg/kubewarden/l10n/en-us.yaml
  pkg/kubewarden/modules/policyReporter.ts
  pkg/kubewarden/types.ts
  pkg/kubewarden/types/kubewarden.ts
  pkg/kubewarden/types/policy-reporter.ts
  pkg/kubewarden/types/wgpolicyk8s.io.ts
  tests/unit/components/PolicyReporter/ResourceTab.spec.ts
  tests/unit/modules/policyReporter.spec.ts
  tests/unit/templates/policyReports.ts
  yarn.lock
Labels: kind/bug, area/policy-reporter

#619 Remove empty objects completely from policy during creation
  jest.config.js
  pkg/kubewarden/utils/object.ts
  tests/unit/_config_/FixJSDOMEnvironment.ts
  tests/unit/_templates_/defaultsApp.js
  tests/unit/_templates_/policyConfig.js
  tests/unit/_templates_/policyPackages.js
  tests/unit/_templates_/policyServerPod.js
  tests/unit/_templates_/policyTraces.js
  tests/unit/_templates_/questions.js
  tests/unit/_templates_/schemas.js
  tests/unit/_utils_/wrapper.ts
  tests/unit/charts/admission/Admission.spec.ts
  tests/unit/charts/admission/General.spec.ts
  tests/unit/charts/admission/NamespaceSelector.spec.ts
  tests/unit/charts/admission/Rules.spec.ts
  tests/unit/components/Dashboard/DashboardView.spec.ts
  tests/unit/components/MetricsChecklist.spec.ts
  tests/unit/components/Policies/Create.spec.ts
  tests/unit/components/Policies/PolicyDetail.spec.ts
  tests/unit/components/Policies/PolicyGrid.spec.ts
  tests/unit/components/Questions/QuestionMap.spec.ts
  tests/unit/components/Questions/SequenceTree.spec.ts
  tests/unit/detail/PolicyServer.spec.ts
  tests/unit/utils/object.spec.ts
Labels: kind/bug, area/policy

#622 Check policies are signed and official
  tests/e2e/00-installation.spec.ts
  tests/e2e/pages/policies.page.ts
Labels: area/qa

#624 Modify run name based on variables
  .github/workflows/playwright.yml
Labels: area/qa

#627 Remove calls to `currentProduct`
  pkg/kubewarden/chart/kubewarden/admission/ContextAware/Resource.vue
  pkg/kubewarden/chart/kubewarden/admission/ContextAware/index.vue
  pkg/kubewarden/chart/kubewarden/admission/General.vue
  pkg/kubewarden/chart/kubewarden/admission/Rules/Rule.vue
  pkg/kubewarden/components/Dashboard/DashboardView.vue
  pkg/kubewarden/components/Dashboard/InstallView.vue
  pkg/kubewarden/components/Policies/Values.vue
  pkg/kubewarden/detail/policies.kubewarden.io.policyserver.vue
  pkg/kubewarden/formatters/PolicyServerStatus.vue
  pkg/kubewarden/list/policies.kubewarden.io.admissionpolicy.vue
  pkg/kubewarden/list/policies.kubewarden.io.clusteradmissionpolicy.vue
  pkg/kubewarden/list/policies.kubewarden.io.policyserver.vue
  pkg/kubewarden/plugins/kubewarden-class.js
  pkg/kubewarden/plugins/policy-server-class.js
  tests/unit/charts/admission/Rules.spec.ts
  tests/unit/components/Dashboard/DashboardView.spec.ts
  tests/unit/detail/PolicyServer.spec.ts
Labels: kind/tech-debt

#625 Fetch artifacthub questions for policy detail views
  pkg/kubewarden/components/Policies/Config.vue
  pkg/kubewarden/components/Policies/Create.vue
  pkg/kubewarden/components/Policies/PolicyDetail.vue
  pkg/kubewarden/components/Policies/Values.vue
  pkg/kubewarden/components/TraceTable.vue
  pkg/kubewarden/types/artifacthub.ts
  pkg/kubewarden/types/kubewarden.ts
  pkg/kubewarden/types/policy.ts
  tests/unit/_templates_/policyConfig.js
  tests/unit/_templates_/policyConfig.ts
  tests/unit/_templates_/policyPackages.ts
  tests/unit/charts/admission/Admission.spec.ts
  tests/unit/charts/admission/General.spec.ts
  tests/unit/charts/admission/NamespaceSelector.spec.ts
  tests/unit/charts/admission/Rules.spec.ts
  tests/unit/components/Policies/Config.spec.ts
  tests/unit/components/Policies/Create.spec.ts
  tests/unit/components/Policies/PolicyGrid.spec.ts
Labels: kind/bug, area/policy

#628 Fix github e2e run name
  .github/workflows/playwright.yml
Labels: area/qa

#630 Bump `1.3.5-rc.2`
  package.json
  pkg/kubewarden/package.json
  yarn.lock
Labels: release/patch

#633 Replace `catalog/refresh` call with `catalog/load`
  pkg/kubewarden/components/Dashboard/DashboardView.vue
  tests/unit/_templates_/policyServerPod.ts
  tests/unit/components/Dashboard/DashboardView.spec.ts
Labels: kind/bug

#634 Bump 1.3.5-rc.3
  package.json
  pkg/kubewarden/package.json
Labels: release/patch
