Repository rancher/kubewarden-ui, pull requests merged in 2024-08, with the labels that each got.

#835 Ensure user has availability to display policy reporter page
  pkg/kubewarden/components/PolicyReporter/index.vue
  pkg/kubewarden/l10n/en-us.yaml
  pkg/kubewarden/pages/c/_cluster/kubewarden/index.vue
  tests/unit/components/PolicyReporter/PolicyReporter.spec.ts
Labels: kind/bug, area/policy-reporter, status/backport-candidate

#837 Bump 2.0.0
  package.json
  pkg/kubewarden/package.json
Labels: release/major

#838 Use released rancher 2.9 as default
  .github/workflows/playwright.yml
Labels: area/qa

#842 Add rancher 2.9 to e2e test metrix
  .github/workflows/playwright.yml
  tests/e2e/00-installation.spec.ts
Labels: area/qa

#847 Remove cert-manager test
  tests/e2e/00-installation.spec.ts
  tests/e2e/pages/kubewarden.page.ts
Labels: area/qa

#856 Fix policy server default image from fleet bundle
  pkg/kubewarden/chart/kubewarden/policy-server/General.vue
  pkg/kubewarden/modules/fleet.ts
  tests/unit/_templates_/controllerApp.ts
  tests/unit/_templates_/fleetBundles.ts
  tests/unit/charts/policy-server/General.spec.ts
Labels: area/fleet, area/policy-server, status/backport-candidate

#863 Bump `2.0.1-rc.1`
  package.json
  pkg/kubewarden/package.json
Labels: release/patch

#859 Remove fleet workaround
  tests/e2e/30-policyservers.spec.ts
Labels: area/qa

#866 Add kubewarden 1.16 to upgrade path
  tests/e2e/00-installation.spec.ts
  tests/e2e/40-policies.spec.ts
Labels: area/qa

#870 [Backport] Fix policy server default image from fleet bundle
  pkg/kubewarden/chart/kubewarden/policy-server/General.vue
  pkg/kubewarden/modules/fleet.ts
  tests/unit/_templates_/controllerApp.ts
  tests/unit/_templates_/fleetBundles.ts
  tests/unit/charts/policy-server/General.spec.ts
Labels: status/backport

#868 [Backport] Ensure user has availability to display policy reporter page
  pkg/kubewarden/components/PolicyReporter/index.vue
  pkg/kubewarden/l10n/en-us.yaml
  pkg/kubewarden/pages/c/_cluster/kubewarden/index.vue
  tests/unit/components/PolicyReporter/PolicyReporter.spec.ts
Labels: status/backport

#871 Fix defaultImage selection after creation
  pkg/kubewarden/chart/kubewarden/policy-server/General.vue
  tests/unit/charts/policy-server/General.spec.ts
Labels: kind/bug, area/policy-server, status/backport-candidate

#867 Bump 2.0.1-rc.2
  package.json
  pkg/kubewarden/package.json
Labels: release/patch

#874 [Backport] Fix defaultImage selection after creation
  pkg/kubewarden/chart/kubewarden/policy-server/General.vue
  tests/unit/charts/policy-server/General.spec.ts
Labels: status/backport

#873 Add check for policy-server values
  tests/e2e/30-policyservers.spec.ts
  tests/e2e/pages/policyservers.page.ts
Labels: area/qa

#875 Bump 1.6.4-rc.1
  package.json
  pkg/kubewarden/package.json
Labels: release/patch

#860 [Backport] Update tests in maintenance branch
  .github/workflows/playwright.yml
  tests/e2e/00-installation.spec.ts
  tests/e2e/30-policyservers.spec.ts
  tests/e2e/60-telemetry.spec.ts
  tests/e2e/components/navigation.ts
  tests/e2e/pages/kubewarden.page.ts
  tests/e2e/pages/policyservers.page.ts
Labels: area/qa

#879 Bump 1.6.4
  package.json
  pkg/kubewarden/package.json
Labels: release/patch

#861 Run tests from maintenance branch on old rancher
  .github/workflows/playwright.yml
Labels: area/qa

#876 Support `matchConditions` for policy spec
  pkg/kubewarden/chart/kubewarden/admission/MatchConditions.vue
  pkg/kubewarden/chart/kubewarden/admission/index.vue
  pkg/kubewarden/components/Policies/Create.vue
  pkg/kubewarden/edit/policies.kubewarden.io.admissionpolicy.vue
  pkg/kubewarden/edit/policies.kubewarden.io.clusteradmissionpolicy.vue
  pkg/kubewarden/l10n/en-us.yaml
  pkg/kubewarden/types/kubewarden.ts
  pkg/kubewarden/types/policy.ts
  tests/unit/charts/admission/MatchConditions.spec.ts
Labels: kind/enhancement, area/policy

#885 Update workflow to use rancher prime 2.9.1
  .github/workflows/playwright.yml
Labels: area/qa

#887 Temporary disable of application-collection
  tests/e2e/components/rancher-ui.ts
Labels: area/qa
