Repository rancher/kubewarden-ui, pull requests merged in 2024-04, with the labels that each got.

#675 Cleanup of e2e workflow file
  .github/workflows/playwright.yml
  tests/README.md
  tests/blob-report/report.zip
  tests/e2e/00-installation.spec.ts
  tests/e2e/30-policyservers.spec.ts
  tests/e2e/40-policies.spec.ts
  tests/e2e/60-telemetry.spec.ts
  tests/package.json
  tests/yarn.lock
Labels: area/qa

#673 Add test for recommended policies settings
  tests/e2e/40-policies.spec.ts
Labels: area/qa

#676 enforce default as namespace for AP creation
  pkg/kubewarden/chart/kubewarden/admission/General.vue
Labels: kind/bug

#678 Add rancher version to test metrix
  .github/workflows/playwright.yml
  tests/README.md
  tests/e2e/40-policies.spec.ts
  tests/e2e/rancher/rancher-fleet.page.ts
Labels: area/qa

#680 Qase reporting integration
  .github/workflows/playwright.yml
  tests/e2e/00-installation.spec.ts
  tests/package.json
  tests/playwright.config.ts
  tests/yarn.lock
Labels: area/qa

#681 Enable dependabot
  .github/dependabot.yml
Labels: area/qa

#692 Add workaround for rancher metrics bug
  tests/e2e/60-telemetry.spec.ts
  tests/e2e/components/navigation.ts
  tests/e2e/components/rancher-ui.ts
  tests/e2e/rancher/rancher-common.page.ts
  tests/global-setup.ts
Labels: area/qa

#694 Skip Container Resources policy test
  tests/e2e/60-telemetry.spec.ts
  tests/e2e/90-allpolicies.spec.ts
Labels: area/qa

#691 Disable editing in UI for KW default policies
  package.json
  pkg/kubewarden/components/DefaultsBanner.vue
  pkg/kubewarden/components/Policies/PolicyList.vue
  pkg/kubewarden/edit/policies.kubewarden.io.clusteradmissionpolicy.vue
  pkg/kubewarden/l10n/en-us.yaml
  pkg/kubewarden/list/policies.kubewarden.io.clusteradmissionpolicy.vue
  pkg/kubewarden/models/policies.kubewarden.io.clusteradmissionpolicy.js
  pkg/kubewarden/modules/policies.ts
  pkg/kubewarden/package.json
  pkg/kubewarden/plugins/policy-class.js
Labels: kind/enhancement

#695 Replace dashboard unit tests
  babel.config.js
  package.json
  tests/unit/components/Dashboard/DashboardView.spec.ts
  yarn.lock
Labels: kind/bug, dependencies

#699 Bump 1.4.3
  package.json
  pkg/kubewarden/package.json
Labels: release/patch

#697 Test recommended policies on 1.12
  .github/workflows/playwright.yml
  tests/e2e/00-installation.spec.ts
  tests/e2e/40-policies.spec.ts
  tests/e2e/components/rancher-ui.ts
Labels: area/qa

#704 Skip recommended policies test on fleet
  tests/e2e/40-policies.spec.ts
  tests/e2e/pages/policies.page.ts
  tests/e2e/rancher/rancher-fleet.page.ts
Labels: area/qa

#705 Fix qase integration
  .github/workflows/playwright.yml
Labels: area/qa

#703 Remove config edit action for policies deployed by fleet
  pkg/kubewarden/components/Policies/PolicyList.vue
  pkg/kubewarden/config/table-headers.ts
  pkg/kubewarden/list/policies.kubewarden.io.admissionpolicy.vue
  pkg/kubewarden/list/policies.kubewarden.io.clusteradmissionpolicy.vue
  pkg/kubewarden/models/policies.kubewarden.io.clusteradmissionpolicy.js
  pkg/kubewarden/plugins/policy-class.js
Labels: kind/bug, area/fleet

#706 Fix qase integration
  .github/workflows/playwright.yml
Labels: area/qa
