Repository rancher/kubewarden-ui, pull requests merged in 2024-12, with the labels that each got.

#1002 Fix typo for ui-extensions-version annotation - bump 2.1.1-rc.1
  package.json
  pkg/kubewarden/package.json
Labels: kind/tech-debt, release/rc

#1001 Update ui-extensions-version annotation - bump 3.0.1-rc.1
  package.json
  pkg/kubewarden/package.json
Labels: kind/tech-debt, release/rc

#1003 Fix upgrade path on rancher >=2.10
  tests/e2e/00-installation.spec.ts
Labels: area/qa

#1007 Update telemetry configuration conditions for tracing and metrics
  pkg/kubewarden/components/MetricsChecklist.vue
  pkg/kubewarden/components/MetricsTab.vue
  pkg/kubewarden/components/TraceChecklist.vue
  pkg/kubewarden/components/TraceTable.vue
  pkg/kubewarden/l10n/en-us.yaml
Labels: kind/bug, status/backport-candidate

#1010 Bump 3.0.2
  package.json
  pkg/kubewarden/package.json
Labels: release/patch

#1011 [Backport] Update telemetry configuration conditions for tracing and metrics
  pkg/kubewarden/components/MetricsChecklist.vue
  pkg/kubewarden/components/MetricsTab.vue
  pkg/kubewarden/components/TraceChecklist.vue
  pkg/kubewarden/components/TraceTable.vue
  pkg/kubewarden/l10n/en-us.yaml
Labels: status/backport

#1012 [Backport] Update telemetry configuration conditions for tracing and metrics
  pkg/kubewarden/components/MetricsChecklist.vue
  pkg/kubewarden/components/MetricsTab.vue
  pkg/kubewarden/components/TraceChecklist.vue
  pkg/kubewarden/components/TraceTable.vue
  pkg/kubewarden/l10n/en-us.yaml
Labels: status/backport

#1014 [backport] Update tests for OTEL changes
  tests/e2e/60-telemetry.spec.ts
  tests/e2e/components/rancher-ui.ts
  tests/e2e/pages/telemetry.page.ts
Labels: area/qa

#1013 [backport] Update tests for OTEL changes
  tests/e2e/60-telemetry.spec.ts
  tests/e2e/components/rancher-ui.ts
  tests/e2e/pages/telemetry.page.ts
Labels: area/qa

#1015 Bump 2.1.2
  package.json
  pkg/kubewarden/package.json
Labels: release/patch

#1016 Bump 1.6.7
  package.json
  pkg/kubewarden/package.json
Labels: release/patch

#1018 Fix fleet for OTEL in Kubewarden 1.20
  tests/e2e/fleet/cert-manager/fleet.yaml
  tests/e2e/fleet/kubewarden/controller/fleet.yaml
Labels: area/qa
