Repository rancher/kubewarden-ui, pull requests merged in 2024-05, with the labels that each got.

#708 Store and filter ClusterPolicyReports for project/namespaces
  pkg/kubewarden/components/PolicyReporter/ReporterPanel.vue
  pkg/kubewarden/components/PolicyReporter/ResourceTab.vue
  pkg/kubewarden/formatters/PolicyReportSummary.vue
  pkg/kubewarden/index.ts
  pkg/kubewarden/l10n/en-us.yaml
  pkg/kubewarden/modules/core.ts
  pkg/kubewarden/modules/policyReporter.ts
  pkg/kubewarden/store/kubewarden/actions.ts
  pkg/kubewarden/store/kubewarden/getters.ts
  pkg/kubewarden/store/kubewarden/index.ts
  pkg/kubewarden/store/kubewarden/mutations.ts
  pkg/kubewarden/types/policy-reporter.ts
  tests/unit/_templates_/policyReports.ts
  tests/unit/components/PolicyReporter/ResourceTab.spec.ts
  tests/unit/modules/policyReporter.spec.ts
Labels: kind/bug, area/policy-reporter

#709 Stabilize nightly test runs
  tests/e2e/00-installation.spec.ts
  tests/e2e/components/kubectl-xterm.ts
  tests/e2e/components/navigation.ts
  tests/e2e/rancher/rancher-common.page.ts
Labels: area/qa

#712 Switch to canvas shell on Rancher 2.9
  tests/e2e/60-telemetry.spec.ts
  tests/e2e/components/kubectl-canvas.ts
  tests/e2e/components/kubectl-shell.ts
  tests/e2e/components/kubectl-xterm.ts
  tests/e2e/components/rancher-ui.ts
  tests/e2e/pages/kubewarden.page.ts
  tests/e2e/rancher/rancher-test.ts
Labels: area/qa

#716 Update outdated documentation links
  README.md
  pkg/kubewarden/l10n/en-us.yaml
Labels: kind/bug, area/documentation

#719 Bump 1.5.0
  package.json
  pkg/kubewarden/package.json
Labels: release/minor

#718 Add upgrade test and nodejs shell
  tests/e2e/00-installation.spec.ts
  tests/e2e/40-policies.spec.ts
  tests/e2e/50-policyreports.spec.ts
  tests/e2e/60-telemetry.spec.ts
  tests/e2e/components/kubectl-shell.ts
  tests/e2e/pages/kubewarden.page.ts
  tests/e2e/rancher/rancher-apps.page.ts
Labels: area/qa

#722 Remove rejected github actions
  .github/workflows/build-extension-charts.yml
  .github/workflows/playwright.yml
  tests/e2e/50-policyreports.spec.ts
  tests/e2e/rancher/rancher-apps.page.ts
Labels: area/qa

#725 Unfreeze opentelemetry version
  tests/e2e/60-telemetry.spec.ts
Labels: area/qa

#724 Initial defaults chart version tied to controller appVersion
  pkg/kubewarden/components/Dashboard/DashboardView.vue
  pkg/kubewarden/components/DefaultsBanner.vue
  pkg/kubewarden/modules/kubewardenController.ts
  pkg/kubewarden/utils/chart.ts
  tests/unit/components/Dashboard/DashboardView.spec.ts
Labels: kind/bug

#729 Fix qase run id parsing
  .github/workflows/playwright.yml
Labels: area/qa

#730 Pin jaeger to version 2.53.0
  .github/workflows/playwright.yml
  tests/e2e/60-telemetry.spec.ts
  tests/package.json
  tests/yarn.lock
Labels: area/qa

#731 Save output of runExec
  tests/e2e/components/kubectl-shell.ts
Labels: area/qa

#733 Fix unstable tests
  tests/e2e/00-installation.spec.ts
  tests/e2e/components/navigation.ts
  tests/e2e/components/rancher-ui.ts
  tests/e2e/components/table-row.ts
  tests/e2e/pages/kubewarden.page.ts
  tests/e2e/pages/policies.page.ts
  tests/e2e/rancher/rancher-apps.page.ts
  tests/e2e/rancher/rancher-extensions.page.ts
Labels: area/qa
