Repository rancher/kubewarden-ui, pull requests merged in 2025-04, with the labels that each got.

#1133 Manually track errors in PolicyServer edit screen
  pkg/kubewarden/components/Dashboard/__tests__/DashboardView.spec.ts
  pkg/kubewarden/edit/policies.kubewarden.io.policyserver.vue
Labels: kind/bug, area/policy-server

#1141 Update side navigation menu item for Kubewarden
  pkg/kubewarden/l10n/en-us.yaml
  tests/e2e/00-installation.spec.ts
  tests/e2e/20-kubewarden.spec.ts
  tests/e2e/30-policyservers.spec.ts
  tests/e2e/40-policies.spec.ts
  tests/e2e/50-policyreports.spec.ts
  tests/e2e/60-telemetry.spec.ts
  tests/e2e/components/navigation.ts
  tests/e2e/pages/kubewarden.page.ts
  tests/e2e/pages/policies.page.ts
  tests/e2e/pages/policyreporter.page.ts
  tests/e2e/pages/policyservers.page.ts
Labels: kind/enhancement, area/ux

#1142 Add linting workflow
  .github/workflows/lint.yml
  .github/workflows/unit-tests.yml
Labels: github_actions

#1143 Add typeLabels to ensure proper menu entries
  pkg/kubewarden/l10n/en-us.yaml
  tests/e2e/00-installation.spec.ts
  tests/e2e/20-kubewarden.spec.ts
  tests/e2e/40-policies.spec.ts
  tests/e2e/components/navigation.ts
  tests/e2e/pages/policies.page.ts
Labels: kind/bug, area/ux

#1147 [2.10] Add new policy to the list
  .github/workflows/playwright.yml
  tests/e2e/00-installation.spec.ts
  tests/e2e/pages/policies.page.ts
Labels: area/qa, status/backport

#1146 [2.9] Add new policy to the list
  tests/e2e/pages/policies.page.ts
Labels: area/qa, status/backport

#1145 [2.8] Add new policy to the list
  tests/e2e/pages/policies.page.ts
Labels: area/qa, status/backport

#1144 Lint e2e tests
  eslint.config.mjs
  package.json
  tests/.eslintrc.js
  tests/e2e/00-installation.spec.ts
  tests/e2e/40-policies.spec.ts
  tests/e2e/50-policyreports.spec.ts
  tests/e2e/60-telemetry.spec.ts
  tests/e2e/90-allpolicies.spec.ts
  tests/e2e/components/kubectl-shell.ts
  tests/e2e/components/navigation.ts
  tests/e2e/components/rancher-ui.ts
  tests/e2e/components/table-row.ts
  tests/e2e/pages/kubewarden.page.ts
  tests/e2e/pages/policies.page.ts
  tests/e2e/pages/policyreporter.page.ts
  tests/e2e/pages/policyservers.page.ts
  tests/e2e/pages/telemetry.page.ts
  tests/e2e/rancher/basepage.ts
  tests/e2e/rancher/rancher-apps.page.ts
  tests/e2e/rancher/rancher-extensions.page.ts
  tests/e2e/rancher/rancher-fleet.page.ts
  tests/e2e/rancher/rancher-test.ts
  tests/unit/mocks/controllerApp.ts
  yarn.lock
Labels: area/qa

#1152 Bump 4.0.0-rc.1
  package.json
  pkg/kubewarden/package.json
Labels: release/rc

#1153 Add rancher 2.11 to test matrix
  .github/workflows/playwright.yml
Labels: area/qa

#1154 Bump 4.0.0
  package.json
  pkg/kubewarden/package.json
Labels: release/major

#1156 Fix updateYamlValuesFromEdit method to update contents of `value`
  pkg/kubewarden/edit/policies.kubewarden.io.clusteradmissionpolicy.vue
Labels: kind/bug, area/policy

#1160 Fix policy readme styling
  pkg/kubewarden/components/Policies/PolicyReadmePanel.vue
Labels: kind/bug, area/policy

#1161 Bump 4.0.1
  package.json
  pkg/kubewarden/package.json
Labels: release/patch

#1166 Update tests to playwright 1.52
  tests/e2e/pages/policyreporter.page.ts
  tests/e2e/rancher/rancher-common.page.ts
Labels: area/qa

#1167 Switch tests to rancher 2.11 prime
  .github/workflows/playwright.yml
Labels: area/qa

#1168 Override otel operator version from env
  tests/e2e/60-telemetry.spec.ts
  tests/e2e/fleet/open-telemetry/fleet.yaml
Labels: area/qa, status/backport-candidate

#1170 [2.9] Override otel operator version from env
  tests/e2e/60-telemetry.spec.ts
Labels: area/qa, status/backport

#1171 [2.10] Override otel operator version from env
  tests/e2e/60-telemetry.spec.ts
Labels: area/qa, status/backport

#1169 [2.8] Override otel operator version from env
  tests/e2e/60-telemetry.spec.ts
Labels: area/qa, status/backport

#1177 Override OTEL operator version
  .github/workflows/playwright.yml
Labels: area/qa, status/backport-candidate

#1176 Override OTEL operator version
  .github/workflows/playwright.yml
Labels: area/qa, status/backport

#1175 Override OTEL operator version
  .github/workflows/playwright.yml
Labels: area/qa, status/backport

#1174 Override OTEL operator version
  .github/workflows/playwright.yml
Labels: area/qa, status/backport
