Repository rancher/kubewarden-ui, pull requests merged in 2025-03, with the labels that each got.

#1086 Fetch kubewarden version map for upgrade test
  tests/e2e/00-installation.spec.ts
  tests/e2e/components/common.ts
Labels: area/qa, area/ui

#1089 Add test path for rancher release-3.1 (rancher 2.10)
  .github/workflows/playwright.yml
Labels: area/qa

#1087 [Forward Port 2.10] Filter out Rego policies - refactor AH fetching
  package.json
  pkg/kubewarden/components/Policies/Create.vue
  pkg/kubewarden/modules/artifacthub.ts
  pkg/kubewarden/package.json
  pkg/kubewarden/store/kubewarden/actions.ts
  pkg/kubewarden/store/kubewarden/getters.ts
  pkg/kubewarden/store/kubewarden/index.ts
  pkg/kubewarden/store/kubewarden/mutations.ts
  pkg/kubewarden/types/artifacthub.ts
  pkg/kubewarden/types/kubewarden.ts
Labels: release/patch, status/forwardport

#1090 Update job names and concurrency
  .github/workflows/playwright.yml
Labels: area/qa

#1091 Release 3.1.1
  package.json
  pkg/kubewarden/package.json
Labels: release/patch

#1092 [Backport] Add test path for release 3.1
  .github/workflows/playwright.yml
  tests/e2e/00-installation.spec.ts
  tests/e2e/components/common.ts
Labels: area/qa, status/backport

#1093 [Forward Port 2.11] Filter out Rego policies - refactor AH fetching
  pkg/kubewarden/components/Policies/Create.vue
  pkg/kubewarden/modules/artifacthub.ts
  pkg/kubewarden/store/kubewarden/actions.ts
  pkg/kubewarden/store/kubewarden/getters.ts
  pkg/kubewarden/store/kubewarden/index.ts
  pkg/kubewarden/store/kubewarden/mutations.ts
  pkg/kubewarden/types/artifacthub.ts
  pkg/kubewarden/types/kubewarden.ts
Labels: status/forwardport

#1095 Paginate artifacthub packages to properly filter out rego policies
  pkg/kubewarden/chart/kubewarden/admission/MatchConditions.vue
  pkg/kubewarden/components/Policies/Create.vue
  pkg/kubewarden/components/Policies/PolicyTable.vue
  pkg/kubewarden/plugins/kubewarden-class.js
  pkg/kubewarden/store/kubewarden/__tests__/actions.spec.ts
  pkg/kubewarden/store/kubewarden/actions.ts
Labels: kind/bug, area/policy, status/backport-candidate

#1084 Add missing unit tests following Vue 3 refactor
  jest.setup.ts
  package.json
  pkg/kubewarden/components/Dashboard/__tests__/DashboardView.spec.ts
  pkg/kubewarden/components/Dashboard/__tests__/Masthead.spec.ts
  pkg/kubewarden/components/Dashboard/__tests__/ReportsGauge.spec.ts
  pkg/kubewarden/components/MetricsChecklist.vue
  pkg/kubewarden/components/MetricsTab.vue
  pkg/kubewarden/components/PolicyReporter/__tests__/PolicyReporter.spec.ts
  pkg/kubewarden/components/PolicyReporter/__tests__/ReporterPanel.spec.ts
  pkg/kubewarden/components/PolicyReporter/__tests__/ResourceTab.spec.ts
  pkg/kubewarden/components/__tests__/DefaultsBanner.spec.ts
  pkg/kubewarden/components/__tests__/InstallWizard.spec.ts
  pkg/kubewarden/components/__tests__/MetricsChecklist.spec.ts
  pkg/kubewarden/components/__tests__/MetricsTab.spec.ts
  pkg/kubewarden/components/__tests__/TraceChecklist.spec.ts
  pkg/kubewarden/components/__tests__/TraceTable.spec.ts
  pkg/kubewarden/formatters/PolicyResources.vue
  pkg/kubewarden/formatters/PolicyServerDeployment.vue
  pkg/kubewarden/formatters/PolicyServerStatus.vue
  pkg/kubewarden/formatters/PolicySummaryGraph.vue
  pkg/kubewarden/formatters/__tests__/PolicyReportSummary.spec.ts
  pkg/kubewarden/formatters/__tests__/PolicyResources.spec.ts
  pkg/kubewarden/formatters/__tests__/PolicyServerDeployment.spec.ts
  pkg/kubewarden/formatters/__tests__/PolicyServerStatus.spec.ts
  pkg/kubewarden/formatters/__tests__/PolicySummaryGraph.spec.ts
  pkg/kubewarden/formatters/__tests__/PolicyTableFeatures.spec.ts
  pkg/kubewarden/formatters/__tests__/PolicyTableResources.spec.ts
  pkg/kubewarden/models/__tests__/policies.kubewarden.io.clusteradmissionpolicy.spec.ts
  pkg/kubewarden/modules/__tests__/core.spec.ts
  pkg/kubewarden/modules/__tests__/fleet.spec.ts
  pkg/kubewarden/modules/__tests__/grafana.spec.ts
  pkg/kubewarden/modules/__tests__/jaegerTracing.spec.ts
  pkg/kubewarden/modules/__tests__/metricsConfig.spec.ts
  pkg/kubewarden/modules/__tests__/policies.spec.ts
  pkg/kubewarden/modules/__tests__/policyReporter.spec.ts
  pkg/kubewarden/plugins/__tests__/kubewarden-class.spec.ts
  pkg/kubewarden/plugins/__tests__/policy-class.spec.ts
  pkg/kubewarden/plugins/__tests__/policy-server-class.spec.ts
  pkg/kubewarden/plugins/kubewarden-class.js
  pkg/kubewarden/store/kubewarden/__tests__/kubewardenStore.spec.ts
  pkg/kubewarden/store/kubewarden/__tests__/mutations.spec.ts
  pkg/kubewarden/store/kubewarden/mutations.ts
  pkg/kubewarden/utils/__tests__/custom-routing.spec.ts
  pkg/kubewarden/utils/__tests__/determine-airgap.spec.ts
  pkg/kubewarden/utils/__tests__/duration-format.spec.ts
  pkg/kubewarden/utils/__tests__/handle-growl.spec.ts
  pkg/kubewarden/utils/__tests__/permissions.spec.ts
  pkg/kubewarden/utils/__tests__/service.spec.ts
  pkg/kubewarden/utils/__tests__/string.spec.ts
  tests/unit/mocks/controllerApp.ts
  yarn.lock
Labels: area/unit-test, kind/tech-debt

#1103 Fix fleet pages for rancher 2.11
  .github/workflows/playwright.yml
  tests/e2e/rancher/rancher-fleet.page.ts
  yarn.lock
Labels: area/qa

#1104 [Backport] Paginate artifacthub packages to properly filter out rego policies
  pkg/kubewarden/chart/kubewarden/admission/MatchConditions.vue
  pkg/kubewarden/components/Policies/Create.vue
  pkg/kubewarden/components/Policies/PolicyTable.vue
  pkg/kubewarden/plugins/kubewarden-class.js
  pkg/kubewarden/store/kubewarden/__tests__/actions.spec.ts
  pkg/kubewarden/store/kubewarden/actions.ts
Labels: area/policy, status/backport

#1106 [Backport] Paginate artifacthub packages to properly filter out rego policies
  pkg/kubewarden/components/Policies/Create.vue
  pkg/kubewarden/components/Policies/PolicyTable.vue
  pkg/kubewarden/plugins/kubewarden-class.js
  pkg/kubewarden/store/kubewarden/actions.ts
Labels: area/policy, status/backport

#1099 Add module to determine PolicyServer resources by labels
  package.json
  pkg/kubewarden/assets/kubewarden-dashboard-policy.json
  pkg/kubewarden/assets/kubewarden-dashboard-policyserver.json
  pkg/kubewarden/components/Dashboard/DashboardView.vue
  pkg/kubewarden/components/Dashboard/__tests__/DashboardView.spec.ts
  pkg/kubewarden/components/MetricsChecklist.vue
  pkg/kubewarden/components/MetricsTab.vue
  pkg/kubewarden/components/TraceTable.vue
  pkg/kubewarden/components/__tests__/MetricsTab.spec.ts
  pkg/kubewarden/components/__tests__/TraceTable.spec.ts
  pkg/kubewarden/l10n/en-us.yaml
  pkg/kubewarden/modules/__tests__/metricsConfig.spec.ts
  pkg/kubewarden/modules/__tests__/policyServer.spec.ts
  pkg/kubewarden/modules/metricsConfig.ts
  pkg/kubewarden/modules/policyServer.ts
  pkg/kubewarden/plugins/__tests__/policy-server-class.spec.ts
  pkg/kubewarden/plugins/policy-server-class.js
  pkg/kubewarden/types.ts
  pkg/kubewarden/types/metrics.ts
  pkg/kubewarden/types/monitoring.coreos.com.ts
  tests/e2e/pages/telemetry.page.ts
  tests/unit/mocks/policyServers.ts
  yarn.lock
Labels: area/policy-server, status/backport-candidate

#1109 UX changes for Dashboard cards - bump 3.1.2
  package.json
  pkg/kubewarden/components/Dashboard/Card.vue
  pkg/kubewarden/components/Dashboard/DashboardView.vue
  pkg/kubewarden/components/Dashboard/Modes.vue
  pkg/kubewarden/components/Dashboard/Reports.vue
  pkg/kubewarden/components/Dashboard/ReportsGauge.vue
  pkg/kubewarden/components/Dashboard/__tests__/DashboardView.spec.ts
  pkg/kubewarden/components/Policies/PolicyList.vue
  pkg/kubewarden/components/SortableTableWrapper.vue
  pkg/kubewarden/config/table-headers.ts
  pkg/kubewarden/package.json
  pkg/kubewarden/utils/__tests__/custom-routing.spec.ts
  pkg/kubewarden/utils/custom-routing.ts
  yarn.lock
Labels: area/ux, release/patch

#1108 Test improvements for rancher 2.11
  .github/workflows/playwright.yml
  tests/e2e/00-installation.spec.ts
  tests/e2e/60-telemetry.spec.ts
  tests/e2e/fleet/open-telemetry/fleet.yaml
Labels: area/qa

#1111 Remove buttons from overview page
  .github/workflows/unit-tests.yml
  tests/e2e/20-kubewarden.spec.ts
  tests/e2e/pages/kubewarden.page.ts
Labels: area/qa

#1116 Add policyServerID to ServiceMonitor creation template name
  jest.config.ts
  pkg/kubewarden/modules/__tests__/metricsConfig.spec.ts
  pkg/kubewarden/modules/metricsConfig.ts
  tsconfig.json
Labels: kind/bug

#1117 [Backport][`2.1`] Add module to determine PolicyServer resources by labels
  pkg/kubewarden/assets/kubewarden-dashboard-policy.json
  pkg/kubewarden/assets/kubewarden-dashboard-policyserver.json
  pkg/kubewarden/components/Dashboard/DashboardView.vue
  pkg/kubewarden/components/MetricsChecklist.vue
  pkg/kubewarden/components/MetricsTab.vue
  pkg/kubewarden/components/TraceTable.vue
  pkg/kubewarden/l10n/en-us.yaml
  pkg/kubewarden/modules/metricsConfig.ts
  pkg/kubewarden/modules/policyServer.ts
  pkg/kubewarden/plugins/policy-server-class.js
  pkg/kubewarden/types.ts
  pkg/kubewarden/types/metrics.ts
  pkg/kubewarden/types/monitoring.coreos.com.ts
  tests/e2e/pages/telemetry.page.ts
Labels: status/backport

#1120 [release-3.1] Downgrade `@rancher/shell` for Rancher 2.10 compatibility
  package.json
  yarn.lock
Labels: dependencies

#1121 Test telemetry with custom PolicyServer
  tests/e2e/60-telemetry.spec.ts
Labels: area/qa

#1122 [UX] Replace policy server consumption gauge with single rows with status icons
  pkg/kubewarden/components/Dashboard/DashboardView.vue
  pkg/kubewarden/components/Dashboard/Masthead.vue
  pkg/kubewarden/components/Dashboard/PolicyServerCard.vue
  pkg/kubewarden/components/Dashboard/__tests__/DashboardView.spec.ts
  pkg/kubewarden/config/table-headers.ts
  pkg/kubewarden/detail/policies.kubewarden.io.policyserver.vue
  pkg/kubewarden/utils/custom-routing.ts
  tests/e2e/10-landing.spec.ts
  tests/e2e/20-kubewarden.spec.ts
  tests/e2e/pages/kubewarden.page.ts
Labels: area/ux

#1125 [Backport][`3.1`] Replace policy server consumption gauge with single rows with status icons
  pkg/kubewarden/components/Dashboard/DashboardView.vue
  pkg/kubewarden/components/Dashboard/Masthead.vue
  pkg/kubewarden/components/Dashboard/PolicyServerCard.vue
  pkg/kubewarden/components/Dashboard/__tests__/DashboardView.spec.ts
  pkg/kubewarden/config/table-headers.ts
  pkg/kubewarden/detail/policies.kubewarden.io.policyserver.vue
  pkg/kubewarden/utils/custom-routing.ts
  tests/e2e/10-landing.spec.ts
  tests/e2e/20-kubewarden.spec.ts
  tests/e2e/pages/kubewarden.page.ts
Labels: status/backport

#1128 Bump 1.6.10
  package.json
  pkg/kubewarden/package.json
Labels: release/patch

#1127 Bump 2.1.5
  package.json
  pkg/kubewarden/package.json
Labels: release/patch

#1126 Bump 3.1.2
  package.json
  pkg/kubewarden/package.json
  yarn.lock
Labels: release/patch

#1129 [2.8] Backport tests
  .github/workflows/playwright.yml
  tests/e2e/00-installation.spec.ts
  tests/e2e/60-telemetry.spec.ts
  tests/e2e/components/common.ts
  tests/e2e/pages/kubewarden.page.ts
Labels: area/qa, status/backport

#1130 [2.9] Backport tests
  .github/workflows/playwright.yml
  tests/e2e/00-installation.spec.ts
  tests/e2e/60-telemetry.spec.ts
  tests/e2e/components/common.ts
  tests/e2e/pages/kubewarden.page.ts
Labels: area/qa, status/backport

#1131 [`gh-pages`] Replace entry for `2.1.5`
  assets/index.yaml
  index.yaml
Labels: kind/bug, release/patch
