Repository rancher/kubewarden-ui, pull requests merged in 2025-02, with the labels that each got.

#1036 Bump kubewarden defaults
  tests/e2e/00-installation.spec.ts
Labels: area/qa

#1038 Prevent test failures from dockerhub rate limit
  .github/workflows/playwright.yml
  tests/e2e/00-installation.spec.ts
  tests/e2e/60-telemetry.spec.ts
  tests/e2e/components/navigation.ts
  tests/e2e/fleet/jaeger-operator/fleet.yaml
  tests/e2e/rancher/rancher-common.page.ts
Labels: area/qa

#1040 Wait for cluster before patching service account
  .github/workflows/playwright.yml
Labels: area/qa

#1041 Authenticate k3d registry to dockerhub
  .github/workflows/playwright.yml
  tests/e2e/60-telemetry.spec.ts
  tests/e2e/fleet/jaeger-operator/fleet.yaml
Labels: area/qa

#1044 Add 302 redirect to successful whitelist domain fetch
  pkg/kubewarden/utils/determine-airgap.ts
Labels: kind/bug, status/backport-candidate

#1046 [Backport][Release 1.6] Add 302 redirect to successful whitelist domain fetch
  pkg/kubewarden/utils/determine-airgap.ts
Labels: status/backport

#1045 [Backport][Release 2.1] Add 302 redirect to successful whitelist domain fetch
  pkg/kubewarden/utils/determine-airgap.ts
Labels: status/backport

#1047 Change user menu locators
  tests/e2e/components/navigation.ts
  tests/e2e/rancher/rancher-common.page.ts
Labels: area/qa

#1050 [backport] Authenticate k3d registry to dockerhub
  .github/workflows/playwright.yml
Labels: area/qa

#1051 Bump 3.0.3
  package.json
  pkg/kubewarden/package.json
Labels: release/patch

#1048 Filter out Rego policies - update store for managing AH packages - cache packages with TTL
  pkg/kubewarden/components/Policies/Create.vue
  pkg/kubewarden/modules/artifacthub.ts
  pkg/kubewarden/store/kubewarden/actions.ts
  pkg/kubewarden/store/kubewarden/getters.ts
  pkg/kubewarden/store/kubewarden/index.ts
  pkg/kubewarden/store/kubewarden/mutations.ts
  pkg/kubewarden/types/artifacthub.ts
  pkg/kubewarden/types/kubewarden.ts
Labels: area/policy, status/backport-candidate

#1052 [Backport 1.6] Filter out Rego policies - refactor AH fetching
  pkg/kubewarden/components/Policies/Create.vue
  pkg/kubewarden/modules/artifacthub.ts
  pkg/kubewarden/store/kubewarden/actions.ts
  pkg/kubewarden/store/kubewarden/getters.ts
  pkg/kubewarden/store/kubewarden/index.ts
  pkg/kubewarden/store/kubewarden/mutations.ts
  pkg/kubewarden/types/artifacthub.ts
  pkg/kubewarden/types/kubewarden.ts
Labels: status/backport

#1054 Bump `1.6.8`
  package.json
  pkg/kubewarden/package.json
Labels: release/patch

#1053 Bump `2.1.3`
  package.json
  pkg/kubewarden/package.json
Labels: release/patch

#1035 Add batching to policy report fetching - fix ref issues
  .eslintignore
  .eslintrc.js
  .prettierrc.json
  eslint.config.mjs
  package.json
  pkg/kubewarden/chart/kubewarden/policy-server/General.vue
  pkg/kubewarden/components/PolicyReporter/ReporterPanel.vue
  pkg/kubewarden/components/PolicyReporter/ResourceTab.vue
  pkg/kubewarden/components/PolicyReporter/index.vue
  pkg/kubewarden/config/table-headers.ts
  pkg/kubewarden/formatters/PolicyReportSummary.vue
  pkg/kubewarden/index.ts
  pkg/kubewarden/l10n/en-us.yaml
  pkg/kubewarden/modules/artifacthub.ts
  pkg/kubewarden/modules/fleet.ts
  pkg/kubewarden/modules/policyReporter.ts
  pkg/kubewarden/store/kubewarden/actions.ts
  pkg/kubewarden/store/kubewarden/getters.ts
  pkg/kubewarden/store/kubewarden/index.ts
  pkg/kubewarden/store/kubewarden/mutations.ts
  pkg/kubewarden/types/policy-reporter.ts
  pkg/kubewarden/utils/determine-airgap.ts
  tests/e2e/50-policyreports.spec.ts
  yarn.lock
Labels: area/policy-reporter

#1057 Update policy-reporter-ui lookup with v3 selectors
  pkg/kubewarden/components/PolicyReporter/index.vue
Labels: area/policy-reporter, status/backport-candidate

#1060 Update tests for policy reporter v3
  tests/e2e/50-policyreports.spec.ts
  tests/e2e/pages/policyreporter.page.ts
Labels: area/qa

#1062 [backport] Updates for policy reporter v3
  pkg/kubewarden/components/PolicyReporter/index.vue
  tests/e2e/50-policyreports.spec.ts
  tests/e2e/pages/policyreporter.page.ts
Labels: area/policy-reporter, status/backport

#1061 [backport] Updates for policy reporter v3
  pkg/kubewarden/components/PolicyReporter/index.vue
  tests/e2e/50-policyreports.spec.ts
  tests/e2e/pages/policyreporter.page.ts
Labels: area/policy-reporter, status/backport

#1063 Ensure resource is determined in PolicyReporter tabs
  pkg/kubewarden/components/PolicyReporter/ResourceTab.vue
Labels: kind/bug, area/policy-reporter

#1064 Bump 2.1.4
  package.json
  pkg/kubewarden/package.json
Labels: release/patch

#1066 Bump 3.0.4
  package.json
  pkg/kubewarden/package.json
Labels: release/patch

#1074 Add kubewarden 1.22 to upgrade path
  tests/e2e/00-installation.spec.ts
  tests/e2e/pages/kubewarden.page.ts
Labels: area/qa

#1075 [backport] Add kubewarden 1.22 to upgrade path
  tests/e2e/00-installation.spec.ts
  tests/e2e/pages/kubewarden.page.ts
Labels: area/qa

#1076 [backport] Add kubewarden 1.22 to upgrade path
  tests/e2e/00-installation.spec.ts
  tests/e2e/pages/kubewarden.page.ts
Labels: area/qa

#1077 Fix kubewarden 1.22 version numbers
  tests/e2e/00-installation.spec.ts
Labels: area/qa

#1078 Fix workarounds for 1.22
  tests/e2e/pages/kubewarden.page.ts
Labels: area/qa

#1083 Lock opentelemetry-operator to 0.80.2
  .github/workflows/playwright.yml
  tests/e2e/60-telemetry.spec.ts
  tests/e2e/components/table-row.ts
  tests/e2e/fleet/open-telemetry/fleet.yaml
Labels: area/qa
